import { join } from 'path';
import { NestFactory, LazyModuleLoader } from '@nestjs/core';
import { ValidationPipe, Logger as NestLogger } from '@nestjs/common';
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { apiReference } from '@scalar/nestjs-api-reference';
import fastifyStatic from '@fastify/static';
import fastifyCookie from '@fastify/cookie';
import { Logger } from 'nestjs-pino';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './common/filters/http-exception.filter';
import { DeferredWarmupService } from './deferred/deferred-warmup.service';
import { initDbCrypto } from './database/crypto/db-crypto';
import {
  buildDbCryptoConfig,
  loadRequiredSecrets,
} from './secrets/secrets.loader';

import { OPENAPI_WEBSOCKET_DOCS } from './common/openapi/websocket-docs';
import { OPENAPI_CLIENT_SDK_DOCS } from './common/openapi/client-sdk-docs';

async function bootstrap() {
  // Before NestFactory: TypeORM email transformers and JwtModule need crypto keys
  // at module init; loading here also keeps secrets out of the Nest config graph.
  await loadRequiredSecrets();
  initDbCrypto(buildDbCryptoConfig());

  const app = await NestFactory.create<NestFastifyApplication>(
    AppModule,
    // trustProxy so req.ip uses X-Forwarded-For from Angie
    new FastifyAdapter({ trustProxy: true }),
    { bufferLogs: true },
  );

  app.useLogger(app.get(Logger));
  app.setGlobalPrefix('api/v1', {
    exclude: ['health', 'ws/(.*)', 'metrics'],
  });
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
      transformOptions: { enableImplicitConversion: true },
    }),
  );
  app.useGlobalFilters(new HttpExceptionFilter());
  app.enableShutdownHooks();

  try {
    // Generated by `nest build` when typeCheck + @nestjs/swagger plugin are enabled.
    // @ts-ignore - file is absent until first SWC build
    const metadata = await import('./metadata');
    await SwaggerModule.loadPluginMetadata(metadata.default);
  } catch {
    // metadata.ts is produced by nest build with typeCheck + swagger plugin
  }

  const swaggerConfig = new DocumentBuilder()
    .setTitle('Leaderboard API')
    .setVersion('1.0')
    .setDescription(
      'Real-time gaming leaderboard REST API.\n\n' +
        '## Password transmission\n\n' +
        'Clients must **never send plaintext passwords**. On `POST /api/v1/auth/signup` and ' +
        '`POST /api/v1/auth/login`, the `password` field is a **domain-separated SHA-256 hex digest** ' +
        '(exactly 64 lowercase hex characters).\n\n' +
        '1. Enforce min 8 characters on the plaintext **before** hashing (client-side).\n' +
        '2. Normalize email: `trim().toLowerCase()`.\n' +
        '3. Hash: SHA-256 over UTF-8 bytes of ' +
        '`leaderboard-v1:` + email + `:` + password → lowercase hex.\n' +
        '4. Send the digest in JSON `password` (field name unchanged).\n\n' +
        'Example: email `player@example.com`, plaintext `securePass123` → ' +
        '`f75088e29caf97691ef9fb92d30c7a7ba0fbfdb7349e0f11361146860a62d750`.\n\n' +
        '```javascript\n' +
        "import { createHash } from 'node:crypto';\n" +
        "const material = 'leaderboard-v1:' + email.trim().toLowerCase() + ':' + plaintext;\n" +
        "createHash('sha256').update(material, 'utf8').digest('hex');\n" +
        '```\n\n' +
        'The server stores **argon2id(prehash)**, not the prehash itself. Client prehashing keeps ' +
        'plaintext out of HTTP logs and SharedWorker memory; the digest is still **password-equivalent** ' +
        'for this API. **TLS is still required** against MITM - prehash is log-safety / domain ' +
        'separation, not transport security or password storage.\n\n' +
        OPENAPI_WEBSOCKET_DOCS +
        '\n\n' +
        OPENAPI_CLIENT_SDK_DOCS,
    )
    .addTag(
      'auth',
      'Signup/login accept a domain-separated SHA-256 password prehash (never plaintext). See Password transmission above.',
    )
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, swaggerConfig);
  const fastify = app.getHttpAdapter().getInstance();

  fastify.get('/openapi.json', async (_req, reply) => reply.send(document));

  app.use(
    '/docs',
    apiReference({
      withFastify: true,
      url: '/openapi.json',
    }),
  );

  // Refresh tokens ride in an HttpOnly cookie set by /api/v1/auth/login; register before static.
  await app.register(fastifyCookie);

  await app.register(fastifyStatic, {
    root: join(__dirname, '..', 'public'),
    prefix: '/',
    decorateReply: false,
    wildcard: false,
  });

  const port = process.env['PORT'] || 3000;
  await app.listen(port, '0.0.0.0');

  // Provider-only warm after listen (Fastify cannot register lazy HTTP routes post-listen)
  try {
    const lazyModuleLoader = app.get(LazyModuleLoader);
    const { DeferredModule } = await import('./deferred/deferred.module');
    const moduleRef = await lazyModuleLoader.load(() => DeferredModule);
    moduleRef.get(DeferredWarmupService).warm();
  } catch (err) {
    NestLogger.warn(
      `Deferred module warm failed: ${err instanceof Error ? err.message : err}`,
      'Bootstrap',
    );
  }
}

void bootstrap();
